version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: spring_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    ports:
      - 5432:5432

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: spring_app
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: passw0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      #KEYCLOAK_IMPORT: /backup/realm/spring-boot-realm.json
      PROXY_ADDRESS_FORWARDING: "true"
      VIRTUAL_HOST: keycloak.local
      VIRTUAL_PORT: 8080
    volumes:
      - ./keycloak/backup:/backup/realm
    expose:
      - 8080
    depends_on:
      - postgres

networks:
  default:
    external:
      name: nginx-proxy