create table simple (
  id bigint generated by default as identity,
  counter bigint not null,
  created_by varchar(4096),
  created_date timestamp,
  modified_by  varchar(4096),
  modified_date timestamp,
  name  varchar(4096) not null,
  version integer not null,
  primary key (id)
)